# Generated by Django 3.2.5 on 2021-08-10 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='picture',
        ),
        migrations.AddField(
            model_name='brand',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شهر دفتر مرکزی'),
        ),
        migrations.AddField(
            model_name='brand',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='کشور دفتر مرکزی'),
        ),
        migrations.AddField(
            model_name='brand',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل دفتر مرکزی'),
        ),
        migrations.AddField(
            model_name='brand',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='تلفن دفتر مرکزی'),
        ),
        migrations.AddField(
            model_name='picture',
            name='discription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
        migrations.AlterField(
            model_name='price',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.FloatField(default=0, help_text='﷼'),
        ),
        migrations.AlterField(
            model_name='price',
            name='set_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='unstable_price',
            field=models.FloatField(blank=True, null=True, verbose_name='قیمت مدت دار'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='upc',
            field=models.PositiveBigIntegerField(help_text='بارکد ۱۲ رقمی'),
        ),
    ]
