# Generated by Django 3.2.5 on 2021-08-19 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210810_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='unstable_price',
        ),
        migrations.AddField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Product'),
        ),
        migrations.AddField(
            model_name='price',
            name='Temporary_price',
            field=models.FloatField(blank=True, null=True, verbose_name='قیمت مموقت'),
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='discription',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='price',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('N', 'Not_Exist'), ('T', 'Active'), ('W', 'Will_not_be_produced'), ('O', 'Ordered')], max_length=1),
        ),
    ]
