# Generated by Django 3.2.6 on 2021-08-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210808_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.FloatField(default=0, help_text='﷼'),
        ),
    ]
