# Generated by Django 3.2.6 on 2021-08-21 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210819_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='Project_Pictures')),
                ('discription', models.CharField(default=None, max_length=100)),
                ('video_description', models.FileField(blank=True, null=True, upload_to='hand_product_video/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
