# Generated by Django 3.2.6 on 2021-08-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210809_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شهر دفتر مرکزی'),
        ),
        migrations.AddField(
            model_name='brand',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل دفتر مرکزی'),
        ),
        migrations.AddField(
            model_name='brand',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='تلفن دفتر مرکزی'),
        ),
        migrations.AddField(
            model_name='brand',
            name='کشور دفتر مرکزی',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='unstable_price',
            field=models.FloatField(blank=True, null=True, verbose_name='قیمت مدت دار'),
        ),
    ]
