# Generated by Django 3.2.6 on 2021-08-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210809_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='city',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='email',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='کشور دفتر مرکزی',
        ),
        migrations.AddField(
            model_name='brand',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='کشور دفتر مرکزی'),
        ),
    ]
