# Generated by Django 3.2.6 on 2021-08-20 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210819_1723'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='prodct_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='score_of_this_cart',
            field=models.PositiveSmallIntegerField(default=0, help_text='امتیاز این سبد خرید را در خودش نگه میداره '),
        ),
    ]
