# Generated by Django 3.2.6 on 2021-08-21 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210821_0824'),
        ('cart', '0002_auto_20210820_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='prodct_fk',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('on_cart', 'on_cart'), ('ready_to_payed', 'ready_to_payed')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='score_of_this_cart',
            field=models.SmallIntegerField(help_text='امتیاز این سبد خرید را در خودش نگه میداره '),
        ),
    ]
